#!/bin/bash

set -e

CONTAINER_NAME="redsea-$RANDOM"
CMD=./do_build.sh


docker run  -it \
            --name ${CONTAINER_NAME} \
            -v `pwd`:/workdir -w /workdir \
            redsea_builder:armhf_trusty ${CMD}

docker rm ${CONTAINER_NAME}
